#!/usr/bin/env bash


# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

echo ""
echo "Installing ARM Cortex Toolchain..."
echo ""

# Updating Repositories
echo "-------------------------------------------------"
echo " Updating Repositories"
echo "-------------------------------------------------"
apt-get update
echo ""

# Install build-essential
echo "-------------------------------------------------"
echo " Installing libncurses and libc..."
echo "-------------------------------------------------"
apt-get -y install libncurses5-dev libncursesw5-dev
if [[ $? != 0 ]]; then
    echo "Error: Can't install libncurses packages."
    echo ""
    exit 1
fi
echo ""
apt-get -y install libc6-dev
if [[ $? != 0 ]]; then
    echo "Error: Can't install libc package."
    echo ""
    exit 1
fi
echo ""


# Install arm-none-eabi-gcc
echo "-------------------------------------------------"
echo " Installing arm-gnu-toolchain..."
echo "-------------------------------------------------"
cd /opt
wget http://ww1.microchip.com/downloads/en/DeviceDoc/arm-gnu-toolchain-6.3.1.508-linux.any.x86_64.tar.gz
if [[ $? != 0 ]]; then
    echo "Error: Can't download arm-gnu-toolchain."
    echo ""
    exit 1
fi
echo "Extracting and installing toolchain..."
tar -xzf arm-gnu-toolchain-6.3.1.508-linux.any.x86_64.tar.gz
if [[ $? != 0 ]]; then
    echo "Error: Can't extract downloaded arm-gnu-toolchain."
    echo ""
    exit 1
fi
ln -sf /opt/arm-none-eabi/bin/* /usr/bin/
rm -f arm-gnu-toolchain-6.3.1.508-linux.any.x86_64.tar.gz
echo ""

echo "ARM Cortex Toolchain components successfully installed."
echo ""

exit 0
