#!/bin/sh

if test -z "$1"
then
    echo "You must provide the wireless interface (i.e. wlan_0)"
    exit 1
else
    WLANDEV=$1
fi

if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with admin privileges."
    exit 1
fi

hcxdumptool -o captured.pcapng -i $WLANDEV –enable_status --disable_client_attacks
