#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with admin privileges."
    exit 1
fi

apt-get update
apt-get -y install pkg-config libcurl4-openssl-dev libssl-dev zlib1g-dev

git clone https://github.com/ZerBea/hcxdumptool.git
cd hcxdumptool
make
make install
cd ..
rm -rf hcxdumptool

git clone https://github.com/ZerBea/hcxtools.git
cd hcxtools
make
make install
cd ..
rm -rf hcxtools

exit 0
