#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

PID=`ps -aux | grep -e "[o]penvpn" | awk 'FNR == 1 {print $2}'`
if [ -z "$PID" ]; then
    nohup openvpn --config conn_cfg.ovpn > /dev/null 2>&1 &
else
    echo "VPN is already connected."
    exit 1
fi

exit 0
