#!/usr/bin/env bash

if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

PID=`ps -aux | grep -e "[o]penvpn" | awk 'FNR == 1 {print $2}'`
if [ ! -z "$PID" ]; then
    kill -9 $PID
    sleep 1
else
    echo "VPN is already disconnected."
    exit 0
fi


PID=`ps -aux | grep -e "[o]penvpn" | awk 'FNR == 1 {print $2}'`
if [ ! -z "$PID" ]; then
    echo "Error - Can't stop the connection."
    exit 1
else
    echo "VPN Disconnected."
fi

exit 0
