#!/usr/bin/env bash
#
# Description:
# Check for high size files in some default system directories.
# If argument is provided, check file sizes of given path.
#

###############################################################################

# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

###############################################################################

# Auxiliary Functions

# Check Disk Usage at specified directory
diskusage()
{
    LOCATION=$1
    DEPTH=$2
    THRESHOLD=$3

    DU="du --all --human-readable --one-file-system"
    DU_OPTS="--max-depth=${DEPTH} --threshold=${THRESHOLD}"

    RESULT=$($DU $DU_OPTS $LOCATION 2>/dev/null | sort -h)
    if [[ -z $RESULT ]]; then
        RESULT="None high size files here"
    fi

    echo ""
    echo "-------------------------------------------------"
    echo "Disk Usage at Directory: ${LOCATION} (size > ${THRESHOLD})"
    echo "-------------------------------------------------"
    echo "${RESULT}"
    echo ""
}

###############################################################################

# Main Functionality

LOCATION="$1"

# Check if argument was provided
if [ $# -gt 0 ]; then
    diskusage $LOCATION 2 1K
else
    diskusage /etc 2 100M
    diskusage /opt 2 100M
    diskusage /var 2 100M
    diskusage /home 2 100M
fi

###############################################################################

exit 0
