#!/usr/bin/env bash

echo ""
echo "Installing/Updating notracking hosts-blocklists files..."
echo ""

# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

# Get the block files
echo "Downloading notracking block files..."
mkdir -p /etc/dnsmasq.d/
cd /etc/dnsmasq.d/
rm -f domains.txt
rm -f hostnames.txt
wget https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt
if [[ $? != 0 ]]; then
    echo "  Error: Can't get hostnames files."
    echo ""
    exit 1
fi
wget https://raw.githubusercontent.com/notracking/hosts-blocklists/master/domains.txt
if [[ $? != 0 ]]; then
    echo "  Error: Can't get domains files."
    echo ""
    exit 1
fi
echo "OK"
echo ""

# Setup dnsmaq
echo "Adding notracking block list files to dnsmasq..."
grep -qxF "conf-file=/etc/dnsmasq.d/domains.txt" /etc/dnsmasq.conf
if [[ $? != 0 ]]; then
    echo "conf-file=/etc/dnsmasq.d/domains.txt" >> /etc/dnsmasq.conf
fi
grep -qxF "addn-hosts=/etc/dnsmasq.d/hostnames.txt" /etc/dnsmasq.conf
if [[ $? != 0 ]]; then
    echo "addn-hosts=/etc/dnsmasq.d/hostnames.txt" >> /etc/dnsmasq.conf
fi
echo "OK"
echo ""

echo "Restarting dnsmasq service..."
service dnsmasq restart
if [[ $? != 0 ]]; then
    echo "  Error: Can't restart dnsmasq."
    echo ""
    systemctl status dnsmasq.service
    echo ""
fi
echo "OK"

echo ""
echo "Done"
echo ""

exit 0
