#!/usr/bin/env bash

###############################################################################

# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

###############################################################################

echo "-------------------------------------------------"
echo "APT Remove Invalid Packages"
echo "-------------------------------------------------"
sudo apt-get -y autoremove
echo ""

echo "-------------------------------------------------"
echo "APT Cache Clean"
echo "-------------------------------------------------"
sudo apt-get clean
echo ""

echo "-------------------------------------------------"
echo "Journal Log Clean Before 1 Day"
echo "-------------------------------------------------"
sudo journalctl --vacuum-time=1d
echo ""

echo "-------------------------------------------------"
echo "Docker Clean Dangling Images"
echo "-------------------------------------------------"
docker rmi -f $(docker images --filter "dangling=true" -q --no-trunc)
echo ""

echo "-------------------------------------------------"
echo "Docker Clean Build Cache"
echo "-------------------------------------------------"
docker builder prune -f
echo ""

###############################################################################

exit 0
