#!/usr/bin/env bash

SCRIPT_NAME=`basename "$0"`
FILE_1=`basename "$1"`
FILE_2=`basename "$2"`
TMP_DIR="${HOME}/gitdiff"

echo "${FILE_1}"
echo "${FILE_2}"
echo "${TMP_DIR}"

if [ $# -lt 2 ]; then
    echo "  You need to provide two files to be compared."
    echo "  Example:"
    echo "    ${SCRIPT_NAME} file_1.txt file_2.txt"
    echo ""
    exit 1
fi

rm -rf $TMP_DIR
mkdir -p $TMP_DIR

cp -a $1 $TMP_DIR
cp -a $2 $TMP_DIR

cd $TMP_DIR
git diff --color-words --no-index $FILE_1 $FILE_2
cd $HOME

rm -rf $TMP_DIR

exit 0
