#!/usr/bin/env bash

if [ $# -lt 2 ]; then
    echo "  You need to provide two files to be compared."
    echo "  Example:"
    echo "    ${0} file_1.txt file_2.txt"
    echo ""
    exit 1
fi

git diff --color-words --no-index $1 $2

exit 0
