#!/usr/bin/env bash

IMG_FILE="$2"
DEVICE="$1"

# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

# Check if correct number of arguments has been provided
if [ $# -ne 2 ]; then
    echo "  You need to provide the image file and virtual device where to flash."
    echo "  Example:"
    echo "  imgread /dev/sdb ./mysystembackup.img"
    echo ""
    exit 1
fi

dd if=$DEVICE bs=1M conv=noerror,fsync oflag=sync status=progress | 7zr a -bd -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on -si $IMG_FILE.7z

exit 0
