#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "  You need to provide a valid hexadecimal number."
    echo "  Example:"
    echo "    ${0} 0xa13c"
    echo ""
    exit 1
fi

python -c "print(int($1))"

exit 0
