#!/usr/bin/env bash

if [ $# -lt 1 ]; then
    echo "  You need to provide a valid hexadecimal number."
    echo "  Example:"
    echo "    ${0} 0x3f2a"
    echo ""
    exit 1
fi

python3 -c "print(bin(${1}))"

exit 0
