#!/usr/bin/env bash


# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

echo ""
echo "Installing ARM Cortex Toolchain..."
echo ""

# Updating Repositories
echo "-------------------------------------------------"
echo " Updating Repositories"
echo "-------------------------------------------------"
apt-get update
echo ""

# Install build-essential
echo "-------------------------------------------------"
echo " Installing libncurses, libc and libudev-dev..."
echo "-------------------------------------------------"
apt-get -y install libncurses5 libncurses5-dev libncursesw5-dev
if [[ $? != 0 ]]; then
    echo "Error: Can't install libncurses packages."
    echo ""
    exit 1
fi
echo ""
apt-get -y install libc6 libc6-dev
if [[ $? != 0 ]]; then
    echo "Error: Can't install libc package."
    echo ""
    exit 1
fi
echo ""
apt-get -y install libudev-dev
if [[ $? != 0 ]]; then
    echo "Error: Can't install libudev-dev package."
    echo ""
    exit 1
fi
echo ""


# Install arm-none-eabi-gcc
echo "-------------------------------------------------"
echo " Installing arm-gnu-toolchain..."
echo "-------------------------------------------------"
cd /opt
wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.07/gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2
if [[ $? != 0 ]]; then
    echo "Error: Can't download arm-gnu-toolchain."
    echo ""
    exit 1
fi
echo "Extracting and installing toolchain..."
tar -xf gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2
if [[ $? != 0 ]]; then
    echo "Error: Can't extract downloaded arm-gnu-toolchain."
    echo ""
    exit 1
fi
ln -sf /opt/gcc-arm-none-eabi-10.3-2021.07/bin/* /usr/bin/
rm -f gcc-arm-none-eabi-10.3-2021.07-x86_64-linux.tar.bz2
echo ""


# Install edbg
echo "-------------------------------------------------"
echo " Installing EDBG..."
echo "-------------------------------------------------"
cd /tmp
if [[ $? != 0 ]]; then
    echo "Error: Can't access to /tmp directory."
    echo ""
    exit 1
fi
rm -rf /tmp/edbg
git clone https://github.com/ataradov/edbg
if [[ $? != 0 ]]; then
    echo "Error: Can't clone GIT repository: https://github.com/ataradov/edbg"
    echo ""
    exit 1
fi
cd edbg
make all
if [[ $? != 0 ]]; then
    echo "Error: Can't build edbg."
    echo ""
    exit 1
fi
rm -f /usr/bin/edbg
cp -a ./edbg /usr/bin/
if [[ $? != 0 ]]; then
    echo "Error: Can't place built edbg binary into /usr/bin directory"
    echo ""
    exit 1
fi
chmod +x /usr/bin/edbg
if [[ $? != 0 ]]; then
    echo "Error: Can't give execution permission to edbg tool."
    echo ""
    exit 1
fi
echo ""

echo "ARM Cortex Toolchain components successfully installed."
echo ""

exit 0
