#!/usr/bin/env bash


# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

echo ""
echo "Downloading linuxdeployqt v6..."
echo ""
wget https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage
if [[ $? != 0 ]]; then
    echo "Error: Can't download the file."
    echo ""
    exit 1
fi
mkdir -p /usr/local/sbin/linuxdeployqt
mv linuxdeployqt-6-x86_64.AppImage /usr/local/sbin/linuxdeployqt
chmod +x /usr/local/sbin/linuxdeployqt
echo ""

#########################################################################################

echo ""
echo "Creating deployqt script..."
echo ""

cat << EOF > /usr/local/sbin/qtdeploy
#!/usr/bin/env bash

# Check if correct number of arguments has been provided
if [ \$# -ne 1 ]; then
    echo "  You need to provide the app desktop file."
    echo "  Example:"
    echo "  qtdeploy /usr/local/share/linuxdeployqt/app/usr/share/applications/myapp.desktop"
    echo ""
    exit 1
fi

# Check for root privileges
if [ "\$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

linuxdeployqt \$1 -appimage -extra-plugins=iconengines -no-copy-copyright-files

exit 0
EOF
chmod +x /usr/local/sbin/qtdeploy

echo ""

########################################################################################

echo ""
echo "Setting default App Build File Structure..."
echo ""
mkdir -p /usr/local/share/linuxdeployqt/app/usr/bin
mkdir -p /usr/local/share/linuxdeployqt/app/usr/lib
mkdir -p /usr/local/share/linuxdeployqt/app/usr/share/applications
mkdir -p /usr/local/share/linuxdeployqt/app/usr/share/share/icons/hicolor/256x256/apps
echo ""

exit 0
