#!/usr/bin/env bash

# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

##############################################################################

# APT update function
apt_update()
{
    echo "-------------------------------------------------"
    echo " Updating Repositories"
    echo "-------------------------------------------------"
    apt-get update
    echo ""
}

# APT install package function
apt_install()
{
    if [ $# -gt 0 ]; then
        echo "-------------------------------------------------"
        echo " Installing ${1} package"
        echo "-------------------------------------------------"
        apt-get -y install $1
        if [[ $? != 0 ]]; then
            echo "Error: Can't install ${1} package."
            echo ""
            exit 1
        fi
        echo ""
    fi
}

add_user_to_group()
{
    if [ $# -gt 1 ]; then
        echo "-------------------------------------------------"
        echo " Adding user ${1} to group ${2}"
        echo "-------------------------------------------------"
        if id -nG "${1}" | grep -qw "${2}"; then
            echo "${1} already in group ${2}"
        else
            adduser $1 $2
            if [[ $? != 0 ]]; then
                echo "Error: Can't add user ${1} to ${2}."
                echo ""
                exit 1
            fi
            echo "User ${1} successfully added to group ${2}."
        fi
        echo ""
    fi
}

##############################################################################

echo ""
echo "Installing RTL2832 SDR Tools..."
echo ""
apt_update
apt_install rtl-sdr
apt_install librtlsdr-dev
apt_install cubicsdr
#apt_install gqrx-sdr
#apt_install gnuradio
add_user_to_group $(whoami) plugdev
echo ""
echo "RTL2832 SDR Tools successfully installed."
echo ""
exit 0
