#!/usr/bin/env bash


# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

echo ""
echo "Installing AVR Toolchain..."
echo ""

# Updating Repositories
echo "-------------------------------------------------"
echo " Updating Repositories"
echo "-------------------------------------------------"
apt-get update
echo ""

# Install build-essential
echo "-------------------------------------------------"
echo " Installing binutils..."
echo "-------------------------------------------------"
apt-get -y install binutils
if [[ $? != 0 ]]; then
    echo "Error: Can't install binutils package."
    echo ""
    error=1
fi
echo ""

# Install gcc-avr
echo "-------------------------------------------------"
echo " Installing gcc-avr"
echo "-------------------------------------------------"
apt-get -y install gcc-avr
if [[ $? != 0 ]]; then
    echo "Error: Can't install gcc-avr package."
    echo ""
    error=1
fi
echo ""

# Install avr-libc
echo "-------------------------------------------------"
echo " Installing avr-libc"
echo "-------------------------------------------------"
apt-get -y install avr-libc
if [[ $? != 0 ]]; then
    echo "Error: Can't install avr-libc package."
    echo ""
    error=1
fi
echo ""

# Install avrdude
echo "-------------------------------------------------"
echo " Installing avrdude"
echo "-------------------------------------------------"
apt-get -y install avrdude
if [[ $? != 0 ]]; then
    echo "Error: Can't install avrdude package."
    echo ""
    error=1
fi
echo ""

if [ ! -z "$error" ]; then
    echo ""
    echo "Error: Some AVR Toolchain component has fail to be installeded."
    echo ""
	exit 1
fi

echo ""
echo "AVR Toolchain components successfully installed."
echo ""
exit 0
