#!/usr/bin/env bash


# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

echo ""
echo "Installing Docker..."
echo ""

# Updating Repositories
echo "-------------------------------------------------"
echo " Updating Repositories"
echo "-------------------------------------------------"
echo "apt-get update"
apt-get update
echo ""

# Try Uninstall previous versions
echo "-------------------------------------------------"
echo " Check and try uninstall previous version"
echo "-------------------------------------------------"
echo "apt-get -y remove docker docker-engine docker.io"
apt-get -y remove docker docker-engine docker.io
echo ""

# Install Docker
echo "-------------------------------------------------"
echo " Installing Docker"
echo "-------------------------------------------------"
echo "apt-get -y install docker.io"
apt-get -y install docker.io
if [[ $? != 0 ]]; then
    echo "Error: Can't install Docker packages."
    echo ""
    exit 1
fi
echo ""

# Setup Docker Service
echo "-------------------------------------------------"
echo " Setup Docker Service"
echo "-------------------------------------------------"
echo "systemctl start docker"
systemctl start docker
if [[ $? != 0 ]]; then
    echo "Error: Can't start docker service."
    echo ""
    exit 1
fi
echo "systemctl enable docker"
systemctl enable docker
if [[ $? != 0 ]]; then
    echo "Error: Can't enable docker service."
    echo ""
    exit 1
fi
echo ""


echo ""
echo "Docker successfully installed."
docker --version
echo ""

exit 0
