#!/usr/bin/env bash


# Check for root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be executed with administration privileges."
    echo ""
    exit 1
fi

echo ""
echo "Installing QT5 and dependencies..."
echo ""

# Updating Repositories
echo "-------------------------------------------------"
echo " Updating Repositories"
echo "-------------------------------------------------"
apt-get update
echo ""

# Install build-essential
echo "-------------------------------------------------"
echo " Installing build-essentials"
echo "-------------------------------------------------"
apt-get -y install build-essential
if [[ $? != 0 ]]; then
    echo "Error: Can't install build-essential package."
    echo ""
    exit 1
fi
echo ""

# Install QTCreator
echo "-------------------------------------------------"
echo " Installing qtcreator"
echo "-------------------------------------------------"
apt-get -y install qtcreator
if [[ $? != 0 ]]; then
    echo "Error: Can't install qtcreator package."
    echo ""
    exit 1
fi
echo ""

# Install QT5-Default
echo "-------------------------------------------------"
echo " Installing qt5-default"
echo "-------------------------------------------------"
apt-get -y install qt5-default
if [[ $? != 0 ]]; then
    echo "Error: Can't install qt5-default package."
    echo ""
    exit 1
fi
echo ""

# Install QTBase5-Private-Dev
echo "-------------------------------------------------"
echo " Installing qtbase5-private-dev"
echo "-------------------------------------------------"
apt-get -y install qtbase5-private-dev
if [[ $? != 0 ]]; then
    echo "Error: Can't install qtbase5-private-dev package."
    echo ""
    exit 1
fi
echo ""

echo ""
echo "QT5 successfully installed."
echo ""

exit 0
