#!/usr/bin/env bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
TOKEN=`head -n 1 "${DIR}/token.txt"`

# Check if Token has been set in token file
if [ "$TOKEN" == "NNNNNNNNN:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ]; then
    echo "  You need to set Bot Token in file token.txt."
    echo "  Example:"
    echo "  echo \"123456789:ABCDEfgfLxAupbRw3JKdavbBX5J2757168S\" > token.txt"
    echo ""
    exit 1
fi

curl -s "https://api.telegram.org/bot$TOKEN/getMyCommands" | python -m json.tool

exit 0
