#!/usr/bin/env bash

CHAT_ID="$1"
IMAGE="$2"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
TOKEN=`head -n 1 "${DIR}/token.txt"`
TLG_HOST="api.telegram.org"
TLG_CMD="sendPhoto"

# Check if correct number of arguments has been provided
if [ $# -ne 2 ]; then
    echo "  You need to provide the chat ID and the image to send."
    echo "  Example:"
    echo "  ./bot_say -123456 image.png"
    echo ""
    exit 1
fi

# Check if Token has been set in token file
if [ "$TOKEN" == "NNNNNNNNN:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ]; then
    echo "  You need to set Bot Token in file token.txt."
    echo "  Example:"
    echo "  echo \"123456789:ABCDEfgfLxAupbRw3JKdavbBX5J2757168S\" > token.txt"
    echo ""
    exit 1
fi

curl -s -X POST "https://${TLG_HOST}/bot${TOKEN}/${TLG_CMD}" -F chat_id=$CHAT_ID -F photo="@$IMAGE" | python -m json.tool
echo " "

exit 0
