#!/usr/bin/env bash

CHAT_ID="$1"
MSG_ID="$2"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
TOKEN=`head -n 1 "${DIR}/token.txt"`

# Check if correct number of arguments has been provided
if [ $# -ne 2 ]; then
    echo "  You need to provide the chat ID and the message ID to delete."
    echo "  Example:"
    echo "  ./bot_delete_sg -123456 8513"
    echo ""
    exit 1
fi

# Check if Token has been set in token file
if [ "$TOKEN" == "NNNNNNNNN:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ]; then
    echo "  You need to set Bot Token in file token.txt."
    echo "  Example:"
    echo "  echo \"123456789:ABCDEfgfLxAupbRw3JKdavbBX5J2757168S\" > token.txt"
    echo ""
    exit 1
fi

curl -s "https://api.telegram.org/bot$TOKEN/deleteMessage?chat_id=$CHAT_ID&message_id=$MSG_ID" | python -m json.tool
echo " "

exit 0
