#!/usr/bin/env bash

CHAT_ID="$1"
MEMBER_ID="$2"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
TOKEN=`head -n 1 "${DIR}/token.txt"`

# Check if correct number of arguments has been provided
if [ $# -lt 2 ]; then
    echo "  You need to provide the chat ID and the member/user ID."
    echo "  Example:"
    echo "  ./bot_get_chat_member -1234567890 987654321"
    echo ""
    exit 1
fi

# Check if Token has been set in token file
if [ "$TOKEN" == "NNNNNNNNN:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ]; then
    echo "  You need to set Bot Token in file token.txt."
    echo "  Example:"
    echo "  echo \"123456789:ABCDEfgfLxAupbRw3JKdavbBX5J2757168S\" > token.txt"
    echo ""
    exit 1
fi

curl -s "https://api.telegram.org/bot$TOKEN/getChatMember?chat_id=$CHAT_ID&user_id=$MEMBER_ID" | python -m json.tool
echo " "

exit 0
